### ISSUE TITLE
Qualitative Research

### ISSUE THREAD

**Issue by joelowj** [GIC-CAPSTONE-18/Capstone-Data-Source#1]
This post is on behalf of @Felicity-jt ,

The purpose of this task is to help everyone understand the big picture of application of Deep Learning on Satellite Imagery. Everyone in the Data Source Team will be assigned a paper; understand the idea behind the paper, note down the datasets used in the paper, the corresponding models and accuracies. 

1. <del>[Using Convolutional Networks and Satellite Imagery to Identify Patterns in Urban Environments at a Large Scale](https://arxiv.org/pdf/1704.02965.pdf)</del>(Taken by Yue Ning)

2. <del>[DeepSat - A Learning framework for Satellite Imagery](http://bit.csc.lsu.edu/~saikat/publications/sigproc-sp.pdf) </del>(Taken by Jiang Tao)

3. <del>[Land Use Classification in Remote Sensing Images by Convolutional Neural Networks](https://arxiv.org/pdf/1508.00092.pdf)</del>(Taken by JCube)

4. <del>[Deep Learning the City: Quantifying Urban Perception At A Global Scale](https://pdfs.semanticscholar.org/adb8/7767fe7c302786c4d3b1964baa4f0a2e7aa6.pdf?_ga=2.231487327.1595413655.1505792120-1975569726.1505792120)</del>(Taken by Jia Wen)

Please take time tomorrow (approximately 30minutes ~ 1 hour) to finish reading the paper.

**Comment by joelowj** [comment]
@GilbertZhang and @guoyuanjing2988. I have reviewed the research paper, it will be beneficial to our work. Please take some time to read through them.

**Comment by Felicity-jt** [comment]
I will take the second one :) DeepSat - A Learning framework for Satellite Imagery. Thank you! Ganbatte guys!!

**Comment by leeyn7** [comment]
I'll read up on the first! But im open for exchange if @JwayCube  or @jiawen456 wants it instead.

**Comment by GilbertZhang** [comment]
@joelowj yeah no problem man I will find some time try to read about them~

**Comment by JwayCube** [comment]
I will read the 3rd one on land use classification.

**Comment by jiawen456** [comment]
I will take the last one then
